environment:
  name: prod
  project: cdf-bootcamp-16-prod
  validation-type: prod
  selected:

    - modules/bootcamp/data_foundation
    - modules/bootcamp/ice_cream_api
    - modules/bootcamp/use_cases/oee

variables:
  modules:
    bootcamp:
      # Variables shared by modules
      icapi_ds_external_id: ds_icapi
      icapi_space_name: icapi_dm_space
      data_foundation:
         data_developer_source_id: b26892f4-59c2-45b0-ba37-e77260194c02
      ice_cream_api:
        icapi_extractors_source_id: 261a3753-243b-4f1f-92f4-67fb7d7054de
        tokenUri: ${IDP_TOKEN_URL}
        cdfProjectName: ${CDF_PROJECT}
        scopes: ${IDP_SCOPES}
        icapi_trigger_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
        icapi_trigger_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}
        icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
        icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}

      use_cases:
        oee:
          data_pipeline_oee_source_id: d4c1856e-d1ce-494b-ae15-6666e8eaa2a5
          uc_oee_ds_external_id: ds_uc_oee
          oee_space_name: oee_ts_space
          data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID}
          data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET}
